### ISSUE TITLE
Any plans for kailh sockets and quick swap switches?

### ISSUE THREAD

**Issue by dmgm** [technomancy/atreus#33]
Most people who build a keyboard are also interested in trying different switches, and sometimes mixing switches on a board. [Kailh pcb sockets](https://novelkeys.xyz/products/kailh-pcb-sockets) seem to be a popular way to achieve this, used by the input club and ergdox ez. Are their any plans to produce a socket compatible PCB design?

**Comment by technomancy** [comment]
No, I'm pretty convinced that Matias offer the best feel at this
point. I still offer Cherry-compatible kits because the keycap selection
is not very good yet for Alps-mount.

Adding sockets really doesn't seem like a good use of time since the
number of switches is so low that resoldering isn't as bad as it would
be on most boards. Also because it's designed primarily for travel,
having switches that can come out without desoldering would compromise
its strength.

**Comment by dmgm** [comment]
Your points are very reasonable.

I would just add that a socket based design would mean that your pre-soldered kit, would require no additional soldering (for switches), and so increase the utility to a broader market. Appreciate you make more selling complete kits, but perhaps that isn't so many?

In the event of a faulty switch, or some other board component failure it is much easier to access the cause of the fault, without desoldering and re-soldering switches.
