### ISSUE TITLE
Firmware debounce settings

### ISSUE THREAD

**Issue by ls42** [technomancy/atreus#35]
Personaly, I'm having a lot of issues with bouncing keys. I'm not sure how far this is issue is spread, and I'm also not sure what the exact issue. I've soldered the joints for the keys countless times (okay, maybe 3-4 times, pretty countable) - but it doesn't help every time, and on some days it's worse then on others. Switching keys out didn't help either. Changed the USB cable &rarr; didn't help.

It's also independent of OS (at least on Linux and Windows) of course.

So my question is, would it be possible to debounce to implement a firmware-side debounce? One that

- accepts the first keystroke immediately
- accepts repeated keystrokes made by a human
- ignores keystrokes that are repeated to fast

Thanks

**Comment by technomancy** [comment]
> So my question is, would it be possible to debounce to implement a firmware-side debounce?

Sure; this is already implemented in QMK:

  https://github.com/qmk/qmk_firmware/blob/master/quantum/debounce/debounce_sym_g.c

You could try increasing the DEBOUNCE constant there.

> Personaly, I'm having a lot of issues with bouncing keys. [...] I've
> soldered the joints for the keys countless times (okay, maybe 3-4
> times, pretty countable) - but it doesn't help every time, and on some
> days it's worse then on others. Switching keys out didn't help either.

By switching keys, do you mean that you replaced the entire switch for
that key and still had the chattering problem?

If that's the case, it's possible that the bad solder joint could be in
the diode for a given key rather than on the joint for the switch
itself. That joint would still flex a bit for every key press for the
corresponding key. You might try re-flowing those.

Which keys in particular are affected?

**Comment by ls42** [comment]
Thank for pointing out the DEBOUNCE constant. I will fiddle around with that setting. Gotta read on about how to flash the firmware first, though :)

> By switching keys, do you mean that you replaced the entire switch for that key and still had the chattering problem? 

Uhm, sorry. I didn't switch them out. I'm not sure why I wrote that, maybe I wanted to, but I definitely didn't try new switches. I rember you saying that it were very unlikely that my bouncing issues where key related.


> Which keys in particular are affected?

Well it kinda is all over the place. At the moment, it's the 'i' that's driving me nuts. Most of the time it's either 'i' or 'e' - the two top-most keys. But it also happend to other keys, but more seldom, like the enter key (most bottom-right). Sometimes I have the feeling it's due to the fact that it's my travel keyboard, that I used to take with me every day, to work.

I'll try and resolder some of the diods and also to find the right debounce setting. Hopefully that won't result in a noticable lag.
